### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/UI-Kit#10]
Выложи пожалуйста сюда скрин макета с наложенным PerfectPixel (желательно в инверсии) и с открытым окошком настроек

**Comment by lndbaryshnikov** [comment]
![image](https://user-images.githubusercontent.com/48272925/75622807-6d595280-5bb5-11ea-8421-d44f0fac0e5e.png)
![image](https://user-images.githubusercontent.com/48272925/75622821-8feb6b80-5bb5-11ea-9269-bb1123ff9f34.png)
![image](https://user-images.githubusercontent.com/48272925/75622825-9ed21e00-5bb5-11ea-946c-00f1178814d5.png)
![image](https://user-images.githubusercontent.com/48272925/75622827-a5609580-5bb5-11ea-914d-4904c1b4fc1c.png)
![image](https://user-images.githubusercontent.com/48272925/75622830-a98cb300-5bb5-11ea-995a-320945123ea0.png)
![image](https://user-images.githubusercontent.com/48272925/75622835-b7dacf00-5bb5-11ea-8afd-c29e10f298e8.png)
![image](https://user-images.githubusercontent.com/48272925/75622837-bc06ec80-5bb5-11ea-805e-d79e89a34138.png)

**Comment by lndbaryshnikov** [comment]
![image](https://user-images.githubusercontent.com/48272925/76144123-52438280-608e-11ea-90c0-778fff0e54bb.png)

**Comment by Nelliza** [comment]
Есть несколько бросающихся в глаза моментов: шрифт на кнопках разнится с тем, что на макете, плюс UI для "задизейбленных" кнопок-стрелок должен быть очевидным для пользователя - они не должны реагировать на ховер и курсор также должен быть соответствующим )

**Comment by Nelliza** [comment]
Вообще у свойства `cursor` есть как раз подходящее для `disabled` состояний значение - `not-allowed`, но так тоже норм )

**Comment by Nelliza** [comment]
В макете для выпадающего списка предусмотрена отдельная стилизация:
![1](https://user-images.githubusercontent.com/19621113/87465505-75260a80-c61d-11ea-874f-a990636db76c.png)

**Comment by Nelliza** [comment]
Также в этом же блоке **Search / Drop down** вторая строка поиска должна отличаться от первой и выглядеть так:
![1](https://user-images.githubusercontent.com/19621113/87466011-3ba1cf00-c61e-11ea-9d90-30f7d42215a2.png)
