### ISSUE TITLE
Инлайновые стили

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/UI-Kit#13]
![1](https://user-images.githubusercontent.com/19621113/76359520-702e1300-632c-11ea-9591-f5fd2af38821.png)
Следует избегать инлайновых стилей там, где без них можно обойтись (например там, где значение не меняется динамически), посмотри пожалуйста везде по проекту

**Comment by lndbaryshnikov** [comment]
Правка в коммите выше, случайно 2 действия вместе закоммитил, заметил уже после пуша.

**Comment by lndbaryshnikov** [comment]
Должно быть только в одном месте, это я раньше в svg не очень разбирался, просто взял откуда-то код..
