### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/UI-Kit#16]
По [стайлгайду от Airbnb](https://github.com/airbnb/javascript#variables--unary-increment-decrement), следует заменять инкременты / декременты на запись вида `i += 1`

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/76688229-01a6c900-663c-11ea-8af7-aed311f7dc24.png)
А почему этот миксин принимает сразу 2 объекта, это же не очевидно? )

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/76688316-ade8af80-663c-11ea-9f7b-fbccbca2a4ba.png)
Здесь лучше вместо `if !links` использовать запись вида `- links = links || ...`

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/76688381-32d3c900-663d-11ea-8dcf-39edfa9c65c2.png)
Здесь то же самое с `items`, посмотри плиз весь проект на предмет подобных исправлений

**Comment by lndbaryshnikov** [comment]
> Здесь лучше вместо if !links использовать запись вида - links = links || ...

А чем плох вариант с if?) Если в одну строчку может и лучше второй вариант, но просто, как мне казалось, так смотрится лучше если выражение большое...

**Comment by lndbaryshnikov** [comment]
> А почему этот миксин принимает сразу 2 объекта, это же не очевидно? )

Сначала настройки, потом стили, я такое встречал частенько... 
Думал по смыслу разделить аргументы..)
