### ISSUE TITLE
Переполнение

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/UI-Kit#18]
![1](https://user-images.githubusercontent.com/19621113/77077957-ffab8400-6a06-11ea-8511-a4aad0acfc61.png)
Секция "User Profile" не прошла проверку на переполнение )

**Comment by Nelliza** [comment]
![2](https://user-images.githubusercontent.com/19621113/77078021-16ea7180-6a07-11ea-83e5-4aaffddd6b13.png)
В "Messaging" тоже надо подправить

**Comment by Nelliza** [comment]
Сюда же до кучи про инпуты )
>     * все инпуты проверять, чтобы при заполнении текст не прижимался вплотную к правой границе;
![image](https://user-images.githubusercontent.com/12808495/55307777-c0e18e80-5482-11e9-927f-9c195d81555e.png)

![1](https://user-images.githubusercontent.com/19621113/77082314-f3c2c080-6a0c-11ea-97cd-ab3478e5e32a.png)

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/77661479-bd94bc00-6f8b-11ea-86bb-e86fb970eeee.png)
А почему здесь закомментил? )

**Comment by lndbaryshnikov** [comment]
> А почему здесь закомментил? )

Да это просто когда решал проблему с переполнением, закомментил на время и забыл удалить потом..
