### ISSUE TITLE
Использование js-классов

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/UI-Kit#2]
![1](https://user-images.githubusercontent.com/19621113/73549263-54913c00-4453-11ea-8087-3fe8268ac8c4.png)
Для инкапсуляции состояния следует переписать весь js-код с использованием синтаксиса для классов, чтобы потом можно было для одинаковых компонентов создавать по инстансу класса

**Comment by lndbaryshnikov** [comment]
На последний коммит сослался по ошибке (не относится к теме).

**Comment by Nelliza** [comment]
Не весь код переписал на классы, например, не нашла класса в компоненте **menu-message**

**Comment by Nelliza** [comment]
При именовании переменных не следует добавлять префикс-андерскор, ориентируемся на стайлгайд от Airbnb во всем, что не перекрыто нашими правилами, а у нас в правилах не предусмотрено добавление такого префикса для переменных

**Comment by lndbaryshnikov** [comment]
> При именовании переменных не следует добавлять префикс-андерскор, ориентируемся на стайлгайд от Airbnb во всем, что не перекрыто нашими правилами, а у нас в правилах не предусмотрено добавление такого префикса для переменных

Если я все правильно понял, то в ваших правилах сказано:
> В js нет публичных и частных свойств, поэтому частные методы просто делать с префиксами "_" (нижнее подчеркивание);

Я не использую андерскор при именовании переменных (по крайней мере не помню чтобы так делал в этом проекте, т.к. знаю, что не по правилам), использую "_" только для именования свойств и методов класса, а это вроде как раз одобряется правилами...

**Comment by lndbaryshnikov** [comment]
Или ты под переменными имеешь в виду свойства класса, не метода в прототипе, да?) Либо я не понимаю, потому что вроде не использовал андерскор для именования переменных...

**Comment by Nelliza** [comment]
> Или ты под переменными имеешь в виду свойства класса, не методы в прототипе, да?) Либо я не понимаю, потому что вроде не использовал андерскор для именования переменных...

Да, свойства класса имела в виду, сообщение скопировала с ишью другого стажера, здесь следовало конкретизировать конечно )
