### ISSUE TITLE
Приватные методы

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/UI-Kit#27]
В [JS-стандартах](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/architecture.md) прописано правило - приватные методы начинать с андеркора, здесь отсутствует андерскор:
https://github.com/lndbaryshnikov/UI-Kit/blob/9b94b986c1eba34e3a9c9050203fad94627f4b06/src/components/ui-kit-components/datepicker/Datepicker.js#L11

Посмотри плиз по проекту, где еще может встретиться такое

**Comment by lndbaryshnikov** [comment]
Посмотрел везде, такое больше не встречается)
