### ISSUE TITLE
Правки по макету

### ISSUE THREAD

**Issue by imin314** [lndbaryshnikov/UI-Kit#28]
1) **UPD: Потом только увидела это [ишью](https://github.com/lndbaryshnikov/UI-Kit/issues/14) от Нелли. Соглашусь с ним. Можно не исправлять.** При разрешении экрана от 1095px до 1331px и от 1367px у страницы большие белые поля, но в блоке с кнопками элементы слипаются, а в Arrow Buttons и Percentage / Pie chart содержимое переносится на следующие строки:
![Выделение_631](https://user-images.githubusercontent.com/40715953/91151165-861b6e80-e6e7-11ea-8c92-d6ca0f658ab9.png)

2) Надо добавить cursor: pointer для крестика. Оранжевое текстовое поле, мне кажется, должно сбрасываться, когда юзер фокусируется на поле или начинает ввод. А в выпадающем списке, на сколько помню, у самого ul были еще верхний и нижний паддинги:
![Выделение_634](https://user-images.githubusercontent.com/40715953/91152884-b95efd00-e6e9-11ea-92a4-46633bba2e06.png)

3) У иконок социальных сетей получился странный овальный ховер. Получится сделать круглым? И у птички обрезался клюв:
![Выделение_636](https://user-images.githubusercontent.com/40715953/91154495-caa90900-e6eb-11ea-91a9-3778087d7455.png)

4) В календаре надо проверить шрифты для хэдера и футера. Также у сетки с числами есть свои паддинги (по макету их нет) и она занимает не всю ширину календаря. Высота стрелочных кнопок не совпадает с высотой .ui-datepicker-title, у которого установлен свой фон. Из-за этого, если приглядеться, виден перепад на нижней границе темно-оранжевого контейнера с месяцем.
![Выделение_640](https://user-images.githubusercontent.com/40715953/91155018-78b4b300-e6ec-11ea-85e8-dad798413507.png)

**Comment by imin314** [comment]
2. По search input еще можно убирать оранжевый бэк граунд, т. к. это состояние поля для вывода сообщения "I've not found what I'm looking for.."
Для выпадающего списка надо проверить PixelPerfect, что-то большая разница получилась:
![Выделение_650](https://user-images.githubusercontent.com/40715953/91285414-618ec780-e7b7-11ea-807c-944b743de06d.png)
Там же в "Choose An Option" все слова должны быть с заглавной буквы.

**Comment by imin314** [comment]
1) Здесь что-то произошло с шириной инпутов:
![Выделение_655](https://user-images.githubusercontent.com/40715953/91287667-3d80b580-e7ba-11ea-99b1-7e754886f876.png)

2) Проверь глобально, пожалуйста, соответствие шрифтов макету. Вот здесь, например, в заголовках должен быть Lato-light, кнопки и подзаголовки должны быть жирными:
![Выделение_656](https://user-images.githubusercontent.com/40715953/91287822-6ef98100-e7ba-11ea-8002-3ce81c55696b.png)

**Comment by imin314** [comment]
1) Теперь слетели шрифты:
![Выделение_671](https://user-images.githubusercontent.com/40715953/91705232-e35f6600-eba6-11ea-9a05-54477301e3e0.png)
![Выделение_674](https://user-images.githubusercontent.com/40715953/91705786-a3e54980-eba7-11ea-8b7e-0179ffc9cad6.png)
![Выделение_673](https://user-images.githubusercontent.com/40715953/91705790-a5af0d00-eba7-11ea-9d4a-80235caf9316.png)

2) Для модификатора inverse высота кнопки отличается, поэтому текст кнопки вертикально не выровнен:
![Выделение_672](https://user-images.githubusercontent.com/40715953/91705339-00943480-eba7-11ea-8195-5a131ff54a74.png)

3) Бэкграунд кнопок стал серым. Лучше сделать его прозрачным:
![Выделение_666](https://user-images.githubusercontent.com/40715953/91705608-6680bc00-eba7-11ea-8f1a-bd0d3b6b0888.png)

4) Здесь все-таки не соответствует PixelPerfect, проблема не только в том, что у ul не добавлен padding-top, но и в шрифте. В макете используется SourceSansPro, 14px:
![Выделение_676](https://user-images.githubusercontent.com/40715953/91706934-4c47dd80-eba9-11ea-97d2-1b4d6feb68e5.png)
Надо прям глобально проверить шрифты.

**Comment by lndbaryshnikov** [comment]
Все поправил, шрифты перепроверил по всему макету. 

> Для модификатора inverse высота кнопки отличается, поэтому текст кнопки вертикально не выровнен

Высота кнопки одинаковая для всех кнопок. Это просто так кажется из-за контраста границ, выравнивание везде одинаковое, также и на самом макете. Но я немного поправил чтобы смотрелось нормально.

**Comment by imin314** [comment]
Еще остались правки по макету:
Размер шрифта в инпутах должен быть 14px:
![Выделение_740](https://user-images.githubusercontent.com/40715953/93083581-01f05180-f6bd-11ea-8574-3bdb25ecc46a.png)

У карты и календаря тоже закругленные углы:
![Выделение_741](https://user-images.githubusercontent.com/40715953/93083612-0f0d4080-f6bd-11ea-869e-2102ceb127e3.png)

Этот эффект, мне кажется, выглядит сыро:
![Выделение_742](https://user-images.githubusercontent.com/40715953/93083710-36640d80-f6bd-11ea-85f1-0c75709666c2.png)
Может, ставить box-shadow по контуру ячейки?

**Comment by imin314** [comment]
Поправь еще цвет выбранного дня в календаре, он должен быть белым. И можешь сам закрыть.
