### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/UI-Kit#3]
**stages.scss**
![1](https://user-images.githubusercontent.com/19621113/74686681-5133d980-51e3-11ea-84ed-4fcc3f62e9ef.png)
Согласно БЭМ-методологии, блоки должны быть полностью автономными и могут влиять только на собственные элементы, здесь же у тебя нарушается принцип инкапсуляции, [вот тут](https://ru.bem.info/methodology/js/) подробнее об этом

Посмотри пожалуйста везде по проекту, где такое встречается

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/75006455-e43e6f00-5482-11ea-9fcf-6b375ae0da64.png)
Не, так не пойдет, теперь у тебя везде импортанты приткнуты (

**Comment by lndbaryshnikov** [comment]
Пофиксил в 5-ом issue #5
