### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by imin314** [lndbaryshnikov/UI-Kit#31]
1) Каждую кнопку лучше вынести в отдельный блок:
https://github.com/lndbaryshnikov/UI-Kit/blob/eb1d20ce60ac0e151506e2cf6e337d0f804eab26/src/components/ui-kit-components/arrow-buttons/arrow-buttons.pug#L13-L16
Сейчас получается, что, во-первых, в блоке arrow-buttons два раза создается одна и та же кнопка (удобнее было бы задавать направление стрелки модификатором), во-вторых, невозможно использовать кнопки в другом расположении (возможно понадобится между ними вставить какой-то контент).
Блок arrow-buttons можно перенести в site-components, например. А в arrows просто вызывать миксин arrow-button с разными модификаторами.

2) Тут лучше навесить один глобальный модификатор на блок, а для стилизации вложенных элементов воспользоваться наследованием в css. Еще слово news не употребляется в единственном числе (если имеется в виду "новость").
https://github.com/lndbaryshnikov/UI-Kit/blob/eb1d20ce60ac0e151506e2cf6e337d0f804eab26/src/components/ui-kit-components/billboard/billboard.pug#L6-L8

**Comment by lndbaryshnikov** [comment]
Насчет наследования, может я неправильно тебя понял, но вроде проблема решена..
