### ISSUE TITLE
Баги и одно переполнение)

### ISSUE THREAD

**Issue by a-poluhin** [lndbaryshnikov/UI-Kit#33]
Constantin Constantinipolski: 
![image](https://user-images.githubusercontent.com/10168007/93854328-bacb1780-fcdf-11ea-8f86-2863da1187ae.png)

**Comment by a-poluhin** [comment]
Карта налезает на окно чата=)
![image](https://user-images.githubusercontent.com/10168007/93861940-865d5880-fceb-11ea-8573-b20c5babfa7e.png)

**Comment by lndbaryshnikov** [comment]
Пофиксил, теперь все супер
![image](https://user-images.githubusercontent.com/48272925/93891205-d93b0e00-fcf3-11ea-8eb8-506cb4c568b4.png)
