### ISSUE TITLE
Js-файлы

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/UI-Kit#4]
![1](https://user-images.githubusercontent.com/19621113/74687060-63fade00-51e4-11ea-91e0-c5a27a2b2a36.png)
![2](https://user-images.githubusercontent.com/19621113/74687062-64937480-51e4-11ea-9a74-ada542eeefd0.png)
![3](https://user-images.githubusercontent.com/19621113/74687063-652c0b00-51e4-11ea-9216-b75a48b05153.png)
А зачем нужны эти странные файлы с одиночными импортами? )

**Comment by Nelliza** [comment]
![4](https://user-images.githubusercontent.com/19621113/74687258-f602e680-51e4-11ea-894a-941a0dae307d.png)
Здесь же напишу: также не очень понятно, почему папка с `js`- и `scss`-файлами для **ripple-effect** лежит в **styles**?

**Comment by lndbaryshnikov** [comment]
> А зачем нужны эти странные файлы с одиночными импортами? )

Это тот вопрос, который я уже поднимал, про независимость блоков. Например выше в **billboard** импорт **button**, т.к. это зависимость, а блок должен, по БЭМ, содержать в себе все зависимости. Ты сказала что нужно настроить автоимпорт, я так и сделал, но только для страницы ui-kit-demo, так как там задействованы все компоненты, а для остальных страниц сайта я импортировал только необходимые зависимости вручную, их там по несколько штук всего на страницу. Если это не совсем правильно, то подскажи, пожалуйста, как лучше организовать..)

**Comment by lndbaryshnikov** [comment]
> Здесь же напишу: также не очень понятно, почему папка с js- и scss-файлами для ripple-effect лежит в styles?

И тут тоже нужна твоя помощь..) Это просто стиль расходящегося кружочка при клике на кнопки. Он используется в нескольких блоках. Если так неверно, то куда стоит его поместить?)

**Comment by Nelliza** [comment]
> > А зачем нужны эти странные файлы с одиночными импортами? )
> 
> Это тот вопрос, который я уже поднимал, про независимость блоков. Например выше в **billboard** импорт **button**, т.к. это зависимость, а блок должен, по БЭМ, содержать в себе все зависимости. Ты сказала что нужно настроить автоимпорт, я так и сделал, но только для страницы ui-kit-demo, так как там задействованы все компоненты, а для остальных страниц сайта я импортировал только необходимые зависимости вручную, их там по несколько штук всего на страницу. Если это не совсем правильно, то подскажи, пожалуйста, как лучше организовать..)

Ага, и тогда я ответила, что в рамках учебного задания лучше настроить "глобальный" автоимпорт для всего проекта в целом )

**Comment by Nelliza** [comment]
> Это тот вопрос, который я уже поднимал, про независимость блоков. Например выше в **billboard** импорт **button**, т.к. это зависимость, а блок должен, по БЭМ, содержать в себе все зависимости. Ты сказала что нужно настроить автоимпорт, я так и сделал, но только для страницы ui-kit-demo, так как там задействованы все компоненты, а для остальных страниц сайта я импортировал только необходимые зависимости вручную, их там по несколько штук всего на страницу. Если это не совсем правильно, то подскажи, пожалуйста, как лучше организовать..)

Ага, и тогда я ответила, что в рамках учебного задания лучше настроить "глобальный" автоимпорт для всего проекта в целом )

**Comment by Nelliza** [comment]
> > Здесь же напишу: также не очень понятно, почему папка с js- и scss-файлами для ripple-effect лежит в styles?
> 
> И тут тоже нужна твоя помощь..) Это просто стиль расходящегося кружочка при клике на кнопки. Он используется в нескольких блоках. Если так неверно, то куда стоит его поместить?)

Давай перенесем его в папку _vendor_, и _pips-float-plugin_ туда же
